type CodeData = {
  id: number;
  country: string;
  ISDCode: string;
};
export const codes: CodeData[] = [
  { id: 1, country: "Afghanistan", ISDCode: "+993" },
  { id: 2, country: "Åland Islands", ISDCode: "+358" },
  { id: 3, country: "Albania", ISDCode: "+355" },
  { id: 4, country: "Algeria", ISDCode: "+213" },
  { id: 5, country: "American Samoa", ISDCode: "+1" },
  { id: 6, country: "Andorra", ISDCode: "+376" },
  { id: 7, country: "Angola", ISDCode: "+244" },
  { id: 8, country: "Anguilla", ISDCode: "+1" },
  { id: 9, country: "Antigua and Barbuda", ISDCode: "+1" },
  { id: 10, country: "Argentina", ISDCode: "+54" },
  { id: 11, country: "Armenia", ISDCode: "+374" },
  { id: 12, country: "Aruba", ISDCode: "+297" },
  { id: 13, country: "Ascension Island", ISDCode: "+247" },
  { id: 14, country: "Australia", ISDCode: "+61" },
  { id: 15, country: "Australian Antarctic Territory", ISDCode: "+672" },
  { id: 16, country: "Austria", ISDCode: "+43" },
  { id: 17, country: "Azerbaijan", ISDCode: "+994" },
  { id: 18, country: "Bahamas", ISDCode: "+1" },
  { id: 19, country: "Bahrain", ISDCode: "+973" },
  { id: 20, country: "Bangladesh", ISDCode: "+880" },
  { id: 21, country: "Barbados", ISDCode: "+1" },
  { id: 22, country: "Belarus", ISDCode: "+375" },
  { id: 23, country: "Belgium", ISDCode: "+32" },
  { id: 24, country: "Belize", ISDCode: "+501" },
  { id: 25, country: "Benin", ISDCode: "+229" },
  { id: 27, country: "Bhutan", ISDCode: "+975" },
  { id: 28, country: "Bolivia", ISDCode: "+591" },
  { id: 29, country: "Bonaire", ISDCode: "+599" },
  { id: 30, country: "Bosnia and Herzegovina ", ISDCode: "+387" },
  { id: 31, country: "Botswana", ISDCode: "+267" },
  { id: 32, country: "Brazil", ISDCode: "+55" },
  { id: 33, country: "British Indian Ocean Territory", ISDCode: "+246" },
  { id: 34, country: "British Virgin Islands", ISDCode: "+1" },
  { id: 35, country: "Brunei", ISDCode: "+673" },
  { id: 36, country: "Bulgaria", ISDCode: "+359" },
  { id: 37, country: "Burkina Faso", ISDCode: "+226" },
  { id: 38, country: "Burma", ISDCode: "+95" },
  { id: 39, country: "Burundi", ISDCode: "+257" },
  { id: 40, country: "Cambodia", ISDCode: "+855" },
  { id: 41, country: "Cameroon", ISDCode: "+237" },
  { id: 42, country: "Canada", ISDCode: "+1" },
  { id: 43, country: "Canary Islands", ISDCode: "+34" },
  { id: 44, country: "Cape Verde", ISDCode: "+238" },
  { id: 45, country: "Cayman Islands", ISDCode: "+1" },
  { id: 46, country: "Central African Republic", ISDCode: "+236" },
  { id: 47, country: "Ceuta", ISDCode: "+34" },
  { id: 48, country: "Chad", ISDCode: "+235" },
  { id: 49, country: "Chagos Islands", ISDCode: "+246" },
  { id: 50, country: "Chile", ISDCode: "+56" },
  { id: 51, country: "People's Republic of China", ISDCode: "+86" },
  { id: 52, country: "Christmas Island", ISDCode: "+61" },
  { id: 53, country: "Cocos (Keeling) Islands", ISDCode: "+61" },
  { id: 54, country: "Colombia", ISDCode: "+57" },
  { id: 55, country: "Comoros", ISDCode: "+269" },
  { id: 56, country: "Republic of Congo", ISDCode: "+242" },
  { id: 57, country: "Democratic Republic of Congo", ISDCode: "+243" },
  { id: 58, country: "Cook Islands", ISDCode: "+682" },
  { id: 59, country: "Costa Rica", ISDCode: "+506" },
  { id: 60, country: "Croatia", ISDCode: "+385" },
  { id: 61, country: "Cuba", ISDCode: "+53" },
  { id: 62, country: "Curaçao", ISDCode: "+599" },
  { id: 63, country: "Curaçao and the Caribbean Netherlands", ISDCode: "+599" },
  { id: 64, country: "Cyprus", ISDCode: "+357" },
  { id: 65, country: "Czech Republic", ISDCode: "+420" },
  { id: 66, country: "Denmark", ISDCode: "+45" },
  { id: 67, country: "Diego Garcia", ISDCode: "+246" },
  { id: 68, country: "Djibouti", ISDCode: "+253" },
  { id: 69, country: "Dominica", ISDCode: "+1" },
  { id: 70, country: "Dominican Republic", ISDCode: "+1" },
  { id: 71, country: "East Timor", ISDCode: "+670" },
  { id: 72, country: "Easter Island", ISDCode: "+56" },
  { id: 73, country: "Ecuador", ISDCode: "+593" },
  { id: 74, country: "Egypt", ISDCode: "+20" },
  { id: 75, country: "El Salvador", ISDCode: "+503" },
  { id: 76, country: "England", ISDCode: "+44" },
  { id: 77, country: "Equatorial Guinea", ISDCode: "+240" },
  { id: 78, country: "Eritrea", ISDCode: "+291" },
  { id: 79, country: "Estonia", ISDCode: "+372" },
  { id: 80, country: "Ethiopia", ISDCode: "+251" },
  { id: 81, country: "Eswatini", ISDCode: "+268" },
  { id: 82, country: "Falkland Islands", ISDCode: "+500" },
  { id: 83, country: "Faroe Islands", ISDCode: "+298" },
  { id: 84, country: "Federated States of Micronesia", ISDCode: "+691" },
  { id: 85, country: "Fiji", ISDCode: "+679" },
  { id: 86, country: "Finland", ISDCode: "+358" },
  { id: 87, country: "France", ISDCode: "+33" },
  {
    id: 88,
    country: "French Overseas Departments and Territories",
    ISDCode: "+262",
  },
  { id: 89, country: "French Guiana", ISDCode: "+594" },
  { id: 90, country: "French Polynesia", ISDCode: "+689" },
  { id: 91, country: "Gabon", ISDCode: "+241" },
  { id: 92, country: "Gambia", ISDCode: "+220" },
  { id: 93, country: "Georgia", ISDCode: "+995" },
  { id: 94, country: "Germany", ISDCode: "+49" },
  { id: 95, country: "Ghana", ISDCode: "+233" },
  { id: 96, country: "Gibraltar", ISDCode: "+350" },
  { id: 97, country: "Greece", ISDCode: "+30" },
  { id: 98, country: "Greenland", ISDCode: "+299" },
  { id: 99, country: "Grenada", ISDCode: "+1" },
  { id: 100, country: "Guadeloupe", ISDCode: "+590" },
  { id: 101, country: "Guam", ISDCode: "+1" },
  { id: 102, country: "Guatemala", ISDCode: "+502" },
  { id: 103, country: "Guernsey", ISDCode: "+44" },
  { id: 104, country: "Guinea", ISDCode: "+224" },
  { id: 105, country: "Guinea-Bissau", ISDCode: "+245" },
  { id: 106, country: "Guyana", ISDCode: "+592" },
  { id: 107, country: "Haiti", ISDCode: "+509" },
  { id: 108, country: "Hawaii", ISDCode: "+1" },
  { id: 109, country: "Honduras", ISDCode: "+504" },
  { id: 110, country: "Hong Kong", ISDCode: "+852" },
  { id: 111, country: "Hungary", ISDCode: "+36" },
  { id: 112, country: "Iceland", ISDCode: "+354" },
  { id: 113, country: "India", ISDCode: "+91" },
  { id: 114, country: "Indonesia", ISDCode: "+62" },
  { id: 115, country: "Iran", ISDCode: "+98" },
  { id: 116, country: "Iraq", ISDCode: "+964" },
  { id: 117, country: "Ireland", ISDCode: "+353" },
  { id: 118, country: "Isle of Man", ISDCode: "+44" },
  { id: 119, country: "Israel", ISDCode: "+972" },
  { id: 120, country: "Italy", ISDCode: "+39" },
  { id: 121, country: "Ivory Coast", ISDCode: "+225" },
  { id: 122, country: "Jamaica", ISDCode: "+1" },
  { id: 123, country: "Jan Mayen", ISDCode: "+47" },
  { id: 124, country: "Japan", ISDCode: "+81" },
  { id: 125, country: "Jersey", ISDCode: "+44" },
  { id: 126, country: "Jordan", ISDCode: "+962" },
  { id: 127, country: "Kazakhstan", ISDCode: "+7" },
  { id: 128, country: "Kenya", ISDCode: "+254" },
  { id: 129, country: "Kiribati", ISDCode: "+686" },
  { id: 130, country: "Kosovo", ISDCode: "+383" },
  { id: 131, country: "Kuwait", ISDCode: "+965" },
  { id: 132, country: "Kyrgyzstan", ISDCode: "+996" },
  { id: 133, country: "Laos", ISDCode: "+856" },
  { id: 135, country: "Lebanon", ISDCode: "+961" },
  { id: 136, country: "Lesotho", ISDCode: "+266" },
  { id: 137, country: "Liberia", ISDCode: "+231" },
  { id: 138, country: "Libya", ISDCode: "+218" },
  { id: 139, country: "Liechtenstein", ISDCode: "+423" },
  { id: 140, country: "Lithuania", ISDCode: "+370" },
  { id: 141, country: "Luxembourg", ISDCode: "+352" },
  { id: 142, country: "Macau", ISDCode: "+853" },
  { id: 143, country: "Madagascar", ISDCode: "+261" },
  { id: 144, country: "Madeira", ISDCode: "+351" },
  { id: 145, country: "Malawi", ISDCode: "+265" },
  { id: 146, country: "Malaysia", ISDCode: "+60" },
  { id: 147, country: "Maldives", ISDCode: "+960" },
  { id: 148, country: "Mali", ISDCode: "+223" },
  { id: 149, country: "Malta", ISDCode: "+356" },
  { id: 150, country: "Marshall Islands", ISDCode: "+692" },
  { id: 151, country: "Martinique", ISDCode: "+596" },
  { id: 152, country: "Mauritania", ISDCode: "+222" },
  { id: 153, country: "Mauritius", ISDCode: "+230" },
  { id: 154, country: "Mayotte", ISDCode: "+262" },
  { id: 155, country: "Melilla", ISDCode: "+34" },
  { id: 156, country: "Mexico", ISDCode: "+52" },
  { id: 157, country: "Moldova", ISDCode: "+373" },
  { id: 158, country: "Monaco", ISDCode: "+377" },
  { id: 159, country: "Mongolia", ISDCode: "+976" },
  { id: 160, country: "Montenegro", ISDCode: "+382" },
  { id: 161, country: "Montserrat", ISDCode: "+1" },
  { id: 162, country: "Morocco", ISDCode: "+212" },
  { id: 163, country: "Mozambique", ISDCode: "+258" },
  { id: 164, country: "Myanmar", ISDCode: "+95" },
  { id: 165, country: "Artsakh", ISDCode: "+374" },
  { id: 166, country: "Namibia", ISDCode: "+264" },
  { id: 167, country: "Nauru", ISDCode: "+674" },
  { id: 168, country: "Nepal", ISDCode: "+977" },
  { id: 169, country: "Netherlands", ISDCode: "+31" },
  { id: 170, country: "New Caledonia", ISDCode: "+687" },
  { id: 171, country: "New Zealand", ISDCode: "+64" },
  { id: 172, country: "Nicaragua", ISDCode: "+505" },
  { id: 173, country: "Niger", ISDCode: "+227" },
  { id: 174, country: "Nigeria", ISDCode: "+234" },
  { id: 175, country: "Niue", ISDCode: "+683" },
  { id: 176, country: "Norfolk Island", ISDCode: "+672" },
  { id: 177, country: "North Korea", ISDCode: "+850" },
  { id: 178, country: "North Macedonia", ISDCode: "+389" },
  { id: 179, country: "Northern Cyprus", ISDCode: "+90" },
  { id: 180, country: "Northern Ireland", ISDCode: "+44" },
  { id: 181, country: "Northern Mariana Islands", ISDCode: "+1" },
  { id: 182, country: "Norway", ISDCode: "+47" },
  { id: 183, country: "Oman", ISDCode: "+968" },
  { id: 184, country: "Pakistan", ISDCode: "+92" },
  { id: 185, country: "Palau", ISDCode: "+680" },
  { id: 186, country: "Palestine, State of", ISDCode: "++970 / +972" },
  { id: 187, country: "Panama", ISDCode: "+507" },
  { id: 188, country: "Papua New Guinea", ISDCode: "+675" },
  { id: 190, country: "Peru", ISDCode: "+51" },
  { id: 191, country: "Philippines", ISDCode: "+63" },
  { id: 192, country: "Pitcairn Islands", ISDCode: "+64" },
  { id: 193, country: "Plazas de soberanía", ISDCode: "+34" },
  { id: 194, country: "Poland", ISDCode: "+48" },
  { id: 195, country: "Portugal", ISDCode: "+351" },
  { id: 196, country: "Príncipe", ISDCode: "+239" },
  { id: 197, country: "Puerto Rico", ISDCode: "+1" },
  { id: 198, country: "Qatar", ISDCode: "+974" },
  { id: 199, country: "Réunion", ISDCode: "+262" },
  { id: 200, country: "Romania", ISDCode: "+40" },
  { id: 201, country: "Russia (Russian Federation)", ISDCode: "+7" },
  { id: 202, country: "Rwanda", ISDCode: "+250" },
  { id: 203, country: "Saba", ISDCode: "+599" },
  { id: 204, country: "Sahrawi Arab Democratic Republic", ISDCode: "+212" },
  { id: 205, country: "Saint Barthélemy", ISDCode: "+590" },
  {
    id: 206,
    country: "Saint Helena and Tristan da Cunha (not Ascenscion)",
    ISDCode: "+290",
  },
  { id: 207, country: "Saint Kitts and Nevis", ISDCode: "+1" },
  { id: 208, country: "Saint Lucia", ISDCode: "+1" },
  { id: 209, country: "Collectivity of Saint Martin", ISDCode: "+590" },
  { id: 210, country: "Saint Pierre and Miquelon", ISDCode: "+508" },
  { id: 211, country: "Saint Vincent and the Grenadines", ISDCode: "+1" },
  { id: 212, country: "Samoa", ISDCode: "+685" },
  { id: 213, country: "San Marino", ISDCode: "+378" },
  { id: 214, country: "São Tomé and Príncipe", ISDCode: "+239" },
  { id: 215, country: "Saudi Arabia", ISDCode: "+966" },
  { id: 216, country: "Scotland", ISDCode: "+44" },
  { id: 217, country: "Senegal", ISDCode: "+221" },
  { id: 218, country: "Serbia", ISDCode: "+381" },
  { id: 219, country: "Seychelles", ISDCode: "+248" },
  { id: 220, country: "Sierra Leone", ISDCode: "+232" },
  { id: 221, country: "Singapore", ISDCode: "+65" },
  { id: 222, country: "Sint Eustatius", ISDCode: "+599" },
  { id: 223, country: "Sint Maarten", ISDCode: "+1" },
  { id: 224, country: "Slovakia (Slovak Republic)", ISDCode: "+421" },
  { id: 225, country: "Slovenia", ISDCode: "+386" },
  { id: 226, country: "Solomon Islands", ISDCode: "+677" },
  { id: 227, country: "Somalia", ISDCode: "+252" },
  { id: 228, country: "South Africa", ISDCode: "+27" },
  {
    id: 229,
    country: "South Georgia and the South Sandwich Islands",
    ISDCode: "+500",
  },
  { id: 230, country: "South Korea", ISDCode: "+82" },
  { id: 231, country: "South Ossetia", ISDCode: "+995" },
  { id: 232, country: "South Sudan", ISDCode: "+211" },
  { id: 233, country: "Spain", ISDCode: "+34" },
  { id: 234, country: "Sri Lanka", ISDCode: "+94" },
  { id: 235, country: "Sudan", ISDCode: "+249" },
  { id: 236, country: "Suriname", ISDCode: "+597" },
  { id: 237, country: "Svalbard", ISDCode: "+47" },
  { id: 238, country: "Sweden", ISDCode: "+46" },
  { id: 239, country: "Switzerland", ISDCode: "+41" },
  { id: 240, country: "Syria", ISDCode: "+963" },
  { id: 241, country: "Taiwan", ISDCode: "+886" },
  { id: 242, country: "Tajikistan", ISDCode: "+992" },
  { id: 243, country: "Tanzania", ISDCode: "+255" },
  { id: 244, country: "Thailand", ISDCode: "+66" },
  { id: 245, country: "Togo", ISDCode: "+228" },
  { id: 246, country: "Tokelau", ISDCode: "+690" },
  { id: 247, country: "Tonga", ISDCode: "+676" },
  { id: 248, country: "Trinidad and Tobago", ISDCode: "+1" },
  { id: 249, country: "Tristan da Cunha", ISDCode: "+290" },
  { id: 250, country: "Tunisia", ISDCode: "+216" },
  { id: 251, country: "Turkey", ISDCode: "+90" },
  { id: 252, country: "Turkmenistan", ISDCode: "+993" },
  { id: 253, country: "Turks and Caicos Islands", ISDCode: "+1" },
  { id: 254, country: "Tuvalu", ISDCode: "+688" },
  { id: 255, country: "Uganda", ISDCode: "+256" },
  { id: 256, country: "Ukraine", ISDCode: "+380" },
  { id: 257, country: "United Arab Emirates", ISDCode: "+971" },
  { id: 258, country: "United Kingdom", ISDCode: "+44" },
  { id: 259, country: "United States (USA)", ISDCode: "+1" },
  { id: 260, country: "United States Virgin Islands", ISDCode: "+1" },
  { id: 261, country: "Uruguay", ISDCode: "+598" },
  { id: 262, country: "Uzbekistan", ISDCode: "+998" },
  { id: 263, country: "Vanuatu", ISDCode: "+678" },
  { id: 264, country: "Vatican City", ISDCode: "+39" },
  { id: 265, country: "Venezuela", ISDCode: "+58" },
  { id: 266, country: "Vietnam", ISDCode: "+84" },
  { id: 267, country: "U.S. Virgin Islands", ISDCode: "+1" },
  { id: 268, country: "Wales", ISDCode: "+44" },
  { id: 269, country: "Wallis and Futuna", ISDCode: "+681" },
  { id: 270, country: "Western Sahara", ISDCode: "+212" },
  { id: 271, country: "Yemen", ISDCode: "+967" },
  { id: 272, country: "Zambia", ISDCode: "+260" },
  { id: 273, country: "Zimbabwe", ISDCode: "+263" },
];

export const data = [
  {
    id: 1,
    name: "Chibueze",
    company: "ReDI School of Digital Integration GmbH",
    email: "newUser3123456@gmail.co",
    phone: "+4915788073258",
  },
  {
    id: 2,
    name: "Chibueze233",
    company: "ReDI School of Digital Integration GmbH",
    email: "gbeni@gmail.co",
    phone: "+4915788073258",
  },
  {
    id: 8,
    name: "Chibueze233",
    company: "ReDI School of Digital Integration GmbH",
    email: "gbeni@gmail.co",
    phone: "+4915788073258",
  },
];

//let currentContact
export function lastSync(arr: Array<any>) {
  return arr[arr.length - 1];
}
